### ISSUE TITLE
Error using repmat in postprocess.p

### ISSUE THREAD

**Issue by the-lay** [matansel/pix2vertex#1]
Hi! First of all, great paper, awesome results! Never had much interest in machine learning, but this paper actually inspired me to learn more and try it out. I've tried to run this implementation, following the instructions in Readme, but I've stumbled an issue when running the code in Matlab (on Ubuntu 16.04 and Matlab R2012a, latest version of Torch). At the postprocessing step I get error:

```
Error using **repmat**
Too many input arguments.

Error in /home/user/pix2vertex/postprocess.p>postprocess (line 38)

Error in **runme** (line 42)
[vertex, face, texture] = postprocess(img, im_pncc, im_depth, show_figs);
```

I don't have much experience with Matlab, but according to docs, .p file is a protected file, so I don't really have access and can't really debug what's going on down there. Would be great if you give some pointers!

My best, Ilja

**Comment by eladrich** [comment]
Hi Ilja, Thanks for the feedback! Glad to here we captured your interest :)

The project was tested on Ubuntu 14.04 with Matlab R2015b (updated the Readme).
From the Matlab documentation it appears we are using a syntax for repmat that was added only in R2013b,  `B = repmat(A,r1,...,rN)` instead of the standard `B = repmat(A,[m n p...])`.

I pushed an update to `postprocess.p`, that uses the backward compatible syntax of repmat, which will hopefully solve your problem. We will consider releasing a nonprotected version of postprocess in the future so you could do such tweaks yourself.
